"""Audit existing IXI receipt/fixity/stat evidence; never open archive payloads."""
from pathlib import Path
from datetime import datetime,timezone
from collections import Counter
import hashlib,json,re,shutil,stat,subprocess
R=Path.cwd();P=R/'build/ixi-paired-intake-preparation-v1';B=R/'data/acquisition/ixi-t1-mra-vessel-v1';O=R/'build/ixi-completion-evidence-v1';A=O/'artifacts/ixi-t1-mra-vessel-byte-intake-v1/completion';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert not O.exists(),'preserve prior audit'
 declaration=B/'declaration.json';assert sha(declaration)=='bf6953035d90ce66dcbccee86c4eb69a8cc8b33e020537515e418ab47b4ccdc1'
 d=json.loads(declaration.read_text());identity=json.loads((P/'live-monitor-identity.json').read_text());source=R/d['scope_path'];cohort=R/d['canonical_cohort_path'];scope=json.loads(source.read_text())
 assert sha(source)==d['scope_sha256']=='dfbf2d9d9721a03d7eea313326ef71d570cac2921ca5f520eea41d24a8a5085c';assert sha(cohort)==d['canonical_cohort_sha256']=='b27f28c21089e61f6c4899f172f608cd0f81391588777443939196b1700cb127'
 assert sha(P/'run-intake.py')==d['runner_sha256']=='8101d3c3edfea9d9099848468dbbfe24157bcd552bb16854f94b9c2c5a297dc2'
 for n,h in d['source_files_sha256'].items():assert sha(B/'source'/n)==h
 canonical=B/'completion.json';assert canonical.exists(),'no terminal completion yet';completion=json.loads(canonical.read_text());run=B/'runs'/identity['run_id'];assert canonical.read_bytes()==(run/'completion.json').read_bytes()
 assert completion['status']=='all_bytes_verified' and completion['run_id']==identity['run_id'] and completion['declaration_sha256']==sha(declaration) and completion['cohort_sha256']==sha(cohort)
 assert completion['verified_files']==3 and completion['verified_bytes']==17225109877 and completion['unresolved_files']==0
 assert completion['all_payloads_unreviewed'] and not completion['labels_admitted'] and not completion['training_admitted'] and completion['decoded_array_bytes']==completion['optimizer_updates']==0
 expected={x['filename']:x for x in scope['files']};assert set(expected)=={x['path'] for x in completion['files']};attempts=list(B.glob('attempts/*/*/*-result.json'));intents=list(B.glob('attempts/*/*/*-intent.json'));assert all(p.with_name(p.name.replace('-intent.json','-result.json')).exists() for p in intents)
 all_results={str(p.relative_to(R)):json.loads(p.read_text()) for p in attempts};proofs=[];copies={}
 now=datetime.now(timezone.utc)
 for result in completion['files']:
  name=result['path'];e=expected[name];assert result['status'] in ['byte_verified','existing_byte_verified'] and result['bytes']==e['bytes'] and result['source_md5']==e['expected_md5'] and re.fullmatch('[0-9a-f]{64}',result['sha256'])
  matches=[rel for rel,value in all_results.items() if value==result];assert len(matches)==1,'terminal attempt provenance ambiguous';receipt=R/matches[0];p=B/'verified'/name;s=p.lstat();assert stat.S_ISREG(s.st_mode) and not p.is_symlink() and s.st_size==e['bytes'];assert not p.with_name(name+'.partial').exists();finished=datetime.fromisoformat(result['finished_utc']).timestamp();assert s.st_mtime<=finished and s.st_ctime<=finished
  proof={'schema':'ixi-verified-archive-stat-binding-v1','recorded_utc':now.isoformat(),'archive_path':str(p.relative_to(R)),'verification_receipt_path':str(receipt.relative_to(R)),'verification_receipt_sha256':sha(receipt),'canonical_completion_path':str(canonical.relative_to(R)),'canonical_completion_sha256':sha(canonical),'recorded_archive_sha256':result['sha256'],'recorded_archive_source_md5':result['source_md5'],'expected_bytes':e['bytes'],'verification_finished_utc':result['finished_utc'],'stat':{'device':s.st_dev,'inode':s.st_ino,'mode':s.st_mode,'size':s.st_size,'mtime_ns':s.st_mtime_ns,'ctime_ns':s.st_ctime_ns},'regular_not_symlink':True,'partial_absent':True,'modification_and_metadata_change_times_not_after_verification':True,'source_payload_bytes_read':0,'fresh_payload_rehash':False,'limits':'Uses unchanged transport verification receipt plus current local file identity/stat. Downstream bounded reader must bind and recheck this stat tuple; this is not a fresh full-file cryptographic verification.'}
  proofs.append(proof);copies[name+'-attempt-result.json']=receipt
 ps=subprocess.run(['ps','-p',str(identity['pid']),'-o','command='],capture_output=True,text=True);command=ps.stdout.strip();exact_alive=bool(command) and hashlib.sha256(command.encode()).hexdigest()==identity['ps_command_stripped_sha256'];assert not exact_alive,'owned downloader has not exited'
 A.mkdir(parents=True)
 for proof in proofs:(A/(Path(proof['archive_path']).name+'-stat-binding.json')).write_text(json.dumps(proof,indent=2,sort_keys=True)+'\n')
 copies.update({'canonical-completion.json':canonical,'run-completion.json':run/'completion.json','started.json':run/'started.json','released-declaration.json':declaration,'process-identity.json':P/'live-monitor-identity.json','root-release-binding.json':P/'root-release-binding.json','audit-source.py':Path(__file__)})
 for name,p in copies.items():shutil.copyfile(p,A/name)
 summary={'schema':'ixi-opaque-byte-intake-completion-audit-v1','audited_utc':now.isoformat(),'status':'all_bytes_verified_unreviewed','canonical_completion_sha256':sha(canonical),'scope_commit':d['scope_commit'],'declaration_sha256':sha(declaration),'scope_sha256':sha(source),'cohort_sha256':sha(cohort),'run_id':identity['run_id'],'verified_files':3,'verified_bytes':17225109877,'archive_hashes':{Path(p['archive_path']).name:{'sha256':p['recorded_archive_sha256'],'source_md5':p['recorded_archive_source_md5'],'bytes':p['expected_bytes'],'stat_binding_sha256':sha(A/(Path(p['archive_path']).name+'-stat-binding.json')),'terminal_attempt_receipt_path':p['verification_receipt_path'],'terminal_attempt_receipt_sha256':p['verification_receipt_sha256']} for p in proofs},'attempt_result_status_counts':dict(Counter(v['status'] for v in all_results.values())),'terminal_process':{'pid':identity['pid'],'pgid':identity['pgid'],'session_id':identity['session_id'],'ps_exit_code':ps.returncode,'exact_original_process_alive':False},'publication_evidence':'Pinned existing transport verifies size/source MD5 on .partial before atomic replace, then records local SHA256. Each final regular file has expected size, no partial remains, and mtime/ctime precede its verification receipt. No bulk rehash was performed.','all_payloads_unreviewed':True,'member_extraction_released':False,'labels_admitted':False,'training_admitted':False,'header_or_array_bytes_opened':0,'archive_body_bytes_opened_by_audit':0,'file_stat_field_mapping_for_reader':{'device':'dev','inode':'ino'},'tracked_files_modified':False}
 (A/'summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
 (A/'RESULT.txt').write_text('All three IXI archives completed verified opaque byte intake: 17,225,109,877 bytes. Canonical and per-run completion records are identical. Per-archive terminal attempt records match the completion, expected source sizes and MD5 references; local SHA256 values are preserved. Stat bindings establish current regular-file identity, size, no residual partial and unchanged modification/metadata-change times since verification. The original downloader is no longer live. No archive body was reopened or freshly rehashed for this audit.\n\nThis is acquisition completion only. Original acquired T1/MRA and derived vessel labels remain unreviewed. No member extraction, image header/voxel decoding, anatomical QC or training admission follows from this receipt. Root separately controls any later bounded reader. Raw fixity authority remains pinned TorchIO with verified HTTPS; label MD5 authority is Zenodo.\n')
 files=[{'path':str(p.relative_to(O)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(O.rglob('*')) if p.is_file()];(O/'hash-manifest.json').write_text(json.dumps({'files':files,'source_payloads_included':False},indent=2)+'\n');print(json.dumps(summary,indent=2));print('bundle_manifest_sha256',sha(O/'hash-manifest.json'))
if __name__=='__main__':main()
