const {app,BrowserWindow}=require('electron');
const fs=require('node:fs');
app.setPath('userData','/tmp/resectionlab-prior-gpu-audit-profile');
const source=fs.readFileSync('/Users/sayemkamal/.codex/.chatgpt-projects/g-p-6ac1ef0d1fc481919c65bf30beca2549/RessectionLab/desktop/src/viewer/shaders.ts','utf8');
const priorAt=source.slice(source.indexOf('bool priorAt('),source.indexOf('void main() {',source.indexOf('bool priorAt(')));
const probe=async function(priorAt){
 const canvas=document.createElement('canvas');canvas.width=1;canvas.height=1;
 const gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true});if(!gl)throw Error('WebGL2 unavailable');
 if(!gl.getExtension('EXT_color_buffer_float'))throw Error('Float framebuffer unavailable');
 const shader=(kind,text)=>{const s=gl.createShader(kind);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'#version 300 es\nvoid main(){vec2 p=gl_VertexID==0?vec2(-1.,-1.):gl_VertexID==1?vec2(3.,-1.):vec2(-1.,3.);gl_Position=vec4(p,0.,1.);}'));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;precision highp sampler3D;uniform sampler3D uPrior;uniform sampler3D uPriorCoverage;uniform int uPriorKind;uniform mat4 uWorldToPrior;uniform vec3 uPriorShape;uniform vec3 uProbeWorld;out vec4 outColor;\n'+priorAt+'\nvoid main(){float v;bool covered=priorAt(uProbeWorld,v);outColor=vec4(covered?1.:0.,v,0.,1.);}'));
 gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const tex=(unit,data,coverage)=>{const texture=gl.createTexture();gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_3D,texture);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texImage3D(gl.TEXTURE_3D,0,coverage?gl.R8:gl.R32F,2,2,2,0,gl.RED,coverage?gl.UNSIGNED_BYTE:gl.FLOAT,data);return texture;};
 gl.uniform1i(gl.getUniformLocation(program,'uPrior'),0);gl.uniform1i(gl.getUniformLocation(program,'uPriorCoverage'),1);gl.uniform3f(gl.getUniformLocation(program,'uPriorShape'),2,2,2);
 const target=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,target);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,1,1,0,gl.RGBA,gl.FLOAT,null);const framebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,target,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Incomplete framebuffer');
 const c=Math.cos(Math.PI/6),s=Math.sin(Math.PI/6),identity=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],inv=[[c/2,s/2,0,-(10*c-20*s)/2],[-s/3,c/3,0,-(-10*s-20*c)/3],[0,0,.25,-1.75],[0,0,0,1]];
 const wave=[0,1,0,1,0,1,0,1],known=Array(8).fill(1);
 const cases=[{name:'functional_center',world:[.5,.5,.5],value:.5},{name:'covered_zero',world:[0,0,0],value:0},{name:'incomplete_support',world:[0,0,.25],coverage:[1,0,1,1,1,1,1,1],covered:false},{name:'binary_low',world:[0,0,.49],kind:1,value:0},{name:'binary_high',world:[0,0,.51],kind:1,value:1},{name:'oblique_covered_boundary',world:[10-3*s,-20+3*c,8],inverse:inv,values:Array(8).fill(.4),coverage:[1,1,1,1,0,0,0,0],value:.4},{name:'tiny_positive',world:[.25,.5,.75],values:Array(8).fill(.00001),value:.00001}];
 for(let n=0;n<32;n++)for(const x of [0,1]){const a=(n+1)*Math.PI/67,c=Math.cos(a),s=Math.sin(a),y=.3,z=.25;cases.push({name:'coverage_boundary_'+n+'_'+x,world:[10+2*c*x-3*s*y,-20+2*s*x+3*c*y,7+4*z],inverse:[[c/2,s/2,0,-(10*c-20*s)/2],[-s/3,c/3,0,-(-10*s-20*c)/3],[0,0,.25,-1.75],[0,0,0,1]],values:Array(8).fill(.4),coverage:x===0?[1,1,1,1,0,0,0,0]:[0,0,0,0,1,1,1,1],value:.4});}
 const results=[];
 for(const test of cases){const values=tex(0,new Float32Array(test.values??wave),false),coverage=tex(1,new Uint8Array(test.coverage??known),true);const m=test.inverse??identity;gl.uniformMatrix4fv(gl.getUniformLocation(program,'uWorldToPrior'),false,new Float32Array([0,1,2,3].flatMap(col=>m.map(row=>row[col]))));gl.uniform3fv(gl.getUniformLocation(program,'uProbeWorld'),test.world);gl.uniform1i(gl.getUniformLocation(program,'uPriorKind'),test.kind??0);gl.viewport(0,0,1,1);gl.drawArrays(gl.TRIANGLES,0,3);const pixel=new Float32Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.FLOAT,pixel);results.push({name:test.name,expectedCovered:test.covered??true,expectedValue:test.value??null,actualCovered:pixel[0]===1,actualValue:pixel[1],glError:gl.getError()});gl.deleteTexture(values);gl.deleteTexture(coverage);}
 return {renderer:gl.getParameter(gl.RENDERER),scope:'actual WebGL2 production priorAt function in1pixel float framebuffer; no application screenshot',results,caseCount:results.length, failedCoverage:results.filter(r=>r.actualCovered!==r.expectedCovered), maxCoveredAbsoluteError:Math.max(...results.filter(r=>r.actualCovered&&r.expectedValue!==null).map(r=>Math.abs(r.actualValue-r.expectedValue)))};
};
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});await win.loadURL('data:text/html,<html><body>prior audit</body></html>');try{const result=await win.webContents.executeJavaScript('('+probe.toString()+')('+JSON.stringify(priorAt)+')');result.sourceFileSha256=require('node:crypto').createHash('sha256').update(source).digest('hex');result.shaderFunctionSha256=require('node:crypto').createHash('sha256').update(priorAt).digest('hex');result.probeSourceSha256=require('node:crypto').createHash('sha256').update(fs.readFileSync(__filename)).digest('hex');result.recordedAt=new Date().toISOString();fs.writeFileSync(require('node:path').join(__dirname,'initial-failed71.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({caseCount:result.caseCount,failedCoverage:result.failedCoverage.length,sourceFileSha256:result.sourceFileSha256,output:require('node:path').join(__dirname,'initial-failed71.json')}));}catch(e){console.error(String(e));process.exitCode=1;}finally{win.destroy();app.quit();}});
setTimeout(()=>{console.error('GPU audit timeout');app.exit(2);},20000).unref();
