"""Root-owned metadata-only final freeze; no model, array or execution import.

Reuses the balanced64 freezer's conservative AST import-closure algorithm.
All four terminal TRAIN endpoints must authenticate before any output is written.
The original pending candidate and candidate source index are never modified.
"""
import argparse
import ast
import hashlib
import json
from pathlib import Path
import subprocess
import sys

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
# Ignore any previously generated bytecode when importing these local stdlib-only
# helpers; no cache directory is created and no canonical model module is imported.
sys.dont_write_bytecode=True
sys.pycache_prefix=str(HERE/'never-written-final-freeze-pycache')
if Path(sys.pycache_prefix).exists() or Path(sys.pycache_prefix).is_symlink():
    raise FileExistsError('Fresh no-write source cache namespace required before helper imports')
sys.path.insert(0,str(HERE))
from comparison_contract import (ARMS,ENDPOINTS,TRAIN,OUTPUT,LIMITS,COHORT,COHORT_SHA,
    PUBLIC_INDEX,PUBLIC_SHA,PARENT_SECONDS,sha,read_pinned,select_public,authenticate_comparison)
from prepare_candidate import endpoint

def relative(path):return path.relative_to(ROOT).as_posix()

def project_module(name):
    if name=='resectionlab':return ROOT/'src/resectionlab/__init__.py'
    if not name.startswith('resectionlab.'):return None
    base=ROOT/'src'/name.replace('.','/')
    if base.with_suffix('.py').is_file():return base.with_suffix('.py')
    if (base/'__init__.py').is_file():return base/'__init__.py'
    return None

def source_closure():
    """Static import closure includes lazy imports and package initializers."""
    paths={HERE/name for name in ('comparison_contract.py','select_worker.py','run_owned.py',
        'prepare_candidate.py','freeze-runtime.py')}
    paths.update(ROOT/'build/goal-conditioned-policy-v1'/name
        for name in ('run_contact_owned.py','darwin_fast_sampler.py'))
    paths.add(ROOT/'src/resectionlab/__init__.py')
    visited=set()
    while paths-visited:
        path=sorted(paths-visited)[0];visited.add(path)
        if path.is_symlink() or not path.is_file():raise ValueError('Regular source required: '+str(path))
        tree=ast.parse(path.read_text());in_package=path.is_relative_to(ROOT/'src/resectionlab')
        if in_package:package='.'.join(path.parent.relative_to(ROOT/'src').parts)
        for node in ast.walk(tree):
            modules=[]
            if isinstance(node,ast.Import):modules.extend(alias.name for alias in node.names)
            elif isinstance(node,ast.ImportFrom):
                if node.level and in_package:
                    base='.'.join(package.split('.')[:len(package.split('.'))-node.level+1])
                    module=base+('.'+node.module if node.module else '')
                elif node.level==0:module=node.module or ''
                else:continue
                modules.append(module)
                modules.extend(module+'.'+alias.name for alias in node.names if alias.name!='*')
            for module in modules:
                dependency=project_module(module)
                if dependency is not None:paths.add(dependency)
    return sorted(paths)

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--head',required=True)
    args=parser.parse_args()
    def head_now():
        return subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True,timeout=5).strip()
    head=head_now()
    if head!=args.head:raise ValueError('Exact root-supplied committed HEAD required')
    output=ROOT/OUTPUT
    for path in (output,output.with_name(output.name+'.supervision'),HERE/'source-index.json',HERE/'release-template.json'):
        if path.exists() or path.is_symlink():raise FileExistsError('Final freeze/attempt path exists: '+str(path))
    pending={name:sha(HERE/name) for name in ('candidate.json','source-index-candidate.json')}
    candidate=json.loads((HERE/'candidate.json').read_text())
    if (candidate['status']!='candidate_not_released' or candidate['arms']!=list(ARMS)
            or candidate['limits']!=LIMITS or candidate['output']!=OUTPUT
            or candidate['public_index']!={'path':PUBLIC_INDEX,'sha256':PUBLIC_SHA}
            or candidate['parent_seconds']!=PARENT_SECONDS or candidate['greedy_seconds']!=60
            or candidate['attempts']!=1 or candidate['automatic_retry'] is not False
            or candidate['planned_SELECT_denominator']!=2 or candidate['held_cases']!=['ReMIND-037']):
        raise ValueError('Original pending fixed six-arm design required')
    baseline='build/cross-patient-planning-v1/fixed-four-train-eight-updates-v1'
    endpoints={ENDPOINTS[0]:endpoint(ENDPOINTS[0],baseline,'IL'),
        ENDPOINTS[1]:endpoint(ENDPOINTS[1],baseline,'RL'),
        ENDPOINTS[2]:endpoint(ENDPOINTS[2],'build/balanced-teacher-il-v1','IL'),
        ENDPOINTS[3]:endpoint(ENDPOINTS[3],'build/balanced-teacher-il64-v1','IL')}
    # This rejects the explicit pending64 sentinel (or failed terminal metadata)
    # before source-index.json or release-template.json is reserved/written.
    authenticate_comparison({'endpoints':endpoints})
    for name in ENDPOINTS[:3]:
        if endpoints[name]!=candidate['endpoints'][name]:
            raise ValueError('Previously pinned eight-update endpoint changed: '+name)
    pending64=candidate['endpoints'][ENDPOINTS[3]]
    if pending64['status']!='pending_terminal_TRAIN_evidence':
        raise ValueError('Original pending64 candidate required')
    for key,path in pending64['expected_paths'].items():
        if endpoints[ENDPOINTS[3]][key]['path']!=path:
            raise ValueError('Fixed64 endpoint path changed')
    if endpoints[ENDPOINTS[3]]['checkpoint']['path']!=pending64['expected_checkpoint']:
        raise ValueError('Fixed64 checkpoint path changed')
    metadata={}
    def bind(ref):
        value=read_pinned(ref)
        if ref['path'] in metadata and metadata[ref['path']]!=ref['sha256']:
            raise ValueError('Conflicting metadata descriptor')
        metadata[ref['path']]=ref['sha256'];return value
    public=bind({'path':PUBLIC_INDEX,'sha256':PUBLIC_SHA});active=select_public(public)
    manifest=bind({'path':active['path'],'sha256':active['sha256']})
    cohort=bind({'path':COHORT,'sha256':COHORT_SHA})
    member=[r for r in cohort['members'] if r['subject']=='ReMIND-013']
    if (len(member)!=1 or member[0]['role']!='SELECT' or member[0]['patient_group']!='ReMIND:013'
            or manifest['patient_id']!='ReMIND-013' or manifest['role']!='SELECT'
            or manifest['patient_group']!='ReMIND:013' or manifest['public_only'] is not True
            or manifest['private_evaluation_files_included'] is not False
            or set(manifest['input_files'])!={'image','supplied_support','supplied_whole_tumor','whole_tumor_domain'}
            or manifest['public_support_domain_fully_covered'] is not True
            or manifest['source_bindings']['cohort_sha256']!=COHORT_SHA):
        raise ValueError('Exact qualified four-array public013 SELECT manifest required')
    # Descriptors alone are checked. Do not stat/hash/open patient arrays here.
    for row in manifest['input_files'].values():
        path=Path(row['path'])
        if not path.is_absolute() or not path.is_relative_to(ROOT) or '..' in path.parts:
            raise ValueError('Qualified workspace public-array descriptor required')
    for refs in endpoints.values():
        original_release=bind(refs['release'])
        for key in ('result','parent','worker_final'):bind(refs[key])
        for ref in refs['contexts'].values():bind(ref)
        bind(original_release['source_index'])
    paths=source_closure();bindings={relative(p):sha(p) for p in paths}
    for path in paths:
        if path.is_relative_to(ROOT/'src'):
            committed=subprocess.check_output(['git','show',head+':'+relative(path)],cwd=ROOT,timeout=5)
            if committed!=path.read_bytes():raise ValueError('Reachable canonical source not committed: '+relative(path))
    if any(sha(ROOT/p)!=v for p,v in bindings.items()) or any(sha(ROOT/p)!=v for p,v in metadata.items()):
        raise ValueError('Source/metadata changed during final freeze')
    if head_now()!=head or any(sha(HERE/name)!=digest for name,digest in pending.items()):
        raise ValueError('HEAD or preserved pending evidence changed')
    index={'version':'public-SELECT013-comparison-runtime-v1','head':head,'source_files':bindings,
        'metadata_files':metadata,'preserved_pending_files':pending,
        'closure_scope':'conservative repository Python import closure including lazy imports; external runtime is recorded by owned execution',
        'scope':'public013 only; held037 remains denominator2; no arrays or checkpoint payload read in freeze'}
    release={**candidate,'status':'pending_root_release','expected_head':head,'endpoints':endpoints,
        'blockers':['root must serialize and release exact final source/HEAD'],
        'source_index':{'path':relative(HERE/'source-index.json'),'sha256':None}}
    encode=lambda value:(json.dumps(value,indent=2,sort_keys=True,allow_nan=False)+'\n').encode()
    index_raw=encode(index);release['source_index']['sha256']=hashlib.sha256(index_raw).hexdigest()
    release_raw=encode(release)
    # Exclusive writes preserve any partial finalization as evidence; never
    # overwrite the pending candidate, a previous final freeze or an attempt.
    with (HERE/'source-index.json').open('xb') as stream:stream.write(index_raw)
    with (HERE/'release-template.json').open('xb') as stream:stream.write(release_raw)
    print(json.dumps({'status':'pending_root_release','head':head,'source_count':len(bindings),
        'metadata_count':len(metadata),'model_loads':0,'patient_array_reads':0,
        'source_index_sha256':hashlib.sha256(index_raw).hexdigest(),
        'release_template_sha256':hashlib.sha256(release_raw).hexdigest(),
        'preserved_pending_files':pending},indent=2))

if __name__=='__main__':main()
