import assert from 'node:assert/strict';import {test} from 'node:test';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
import {checkedFamilyAvailability,requireInteractiveFamilyRequest} from '../src/contact-family-availability.ts';import {unavailableCatalog} from './helpers/contact-family-catalog.mjs';
const text=fs.readFileSync(new URL('../src/ContactFamilyPanel.tsx',import.meta.url),'utf8');
function block(name,next){const a=text.indexOf(`  const ${name} =`),b=text.indexOf(next,a);assert(a>=0&&b>a);return stripTypeScriptTypes(text.slice(a,b));}
function driver(call){const c={api:{publicContactFamilyAvailability:call},generation:{current:0},unavailableReason:undefined,checkedFamilyAvailability,setCatalog:v=>c.catalog=v,setPending:v=>c.pending=v,setError:v=>c.error=v,setLayout:f=>c.layout=f(c.layout),layout:'',catalog:null,error:null};vm.runInNewContext(block('refresh','  useEffect')+'\nglobalThis.refresh=refresh;',c);return c;}
test('actual panel availability fetch selects interactive layout without executing a method',async()=>{let reads=0;const c=driver(async args=>{assert.equal(Object.keys(args).length,0);reads++;return unavailableCatalog()});await c.refresh();assert.equal(reads,1);assert.equal(c.catalog.methods.IL.available,false);assert.equal(c.layout,'pcf-00');assert.equal(c.pending,false);});
test('late availability fetch cannot publish after generation invalidation',async()=>{let release;const c=driver(()=>new Promise(r=>release=r)),pending=c.refresh();c.generation.current++;release(unavailableCatalog());await pending;assert.equal(c.catalog,null);});
test('failed availability leaves all execution unavailable without an invented fallback',async()=>{const c=driver(async()=>{throw Error('CATALOG_FAILED')});await c.refresh();assert.equal(c.catalog,null);assert.equal(c.error,'Error: CATALOG_FAILED');assert.equal(c.pending,false);});
test('actual panel execute revalidates held-out/method admission before callback',()=>{const calls=[],c={catalog:unavailableCatalog(),busy:false,pending:false,reason:null,layout:'pcf-00',goal:'surface',method:'IL',requireInteractiveFamilyRequest,onExecute:(r,v)=>calls.push([r,v]),setError:e=>c.error=e};vm.runInNewContext(block('execute','  const episode')+'\nglobalThis.execute=execute;',c);c.execute();assert.equal(calls.length,0);c.method='SEARCH';c.layout='pcf-20';c.execute();assert.equal(calls.length,0);c.layout='pcf-00';c.execute();assert.equal(calls.length,1);assert.equal(calls[0][0].fixture,'generated-public-contact-family-v2');});
