import assert from 'node:assert/strict';import{test}from'node:test';import{createRequire}from'node:module';
import{hydrateContactFamilyEpisode}from'../src/contact-family-data.ts';import{familyFixture,familyCatalog,familyRequest,familyAssets,resealFamily}from'./helpers/contact-family-fixture.mjs';
const require=createRequire(import.meta.url),{validateFamilyResult}=require('../electron/contact-family.cjs');
const check=f=>hydrateContactFamilyEpisode(f.result,familyAssets(f),familyRequest(f),familyCatalog());
test('planned source STOP is a checked zero outcome; planned SEARCH retains real subvoxel aspiration/probe replay',async()=>{for(const method of ['STOP','SEARCH']){const f=familyFixture(method);validateFamilyResult(f.result,familyRequest(f),familyCatalog());const v=await check(f);assert.deepEqual(v.episode.shape,[15,15,14]);assert.deepEqual(v.observation.channelAvailable,[true,true,true,true,false,false,true,true]);assert.equal(v.episode.learnedAuthorship,null);assert.equal(v.executionProvenance,null);assert.equal(v.episode.metrics.target_removed_mm3,undefined);if(method==='STOP'){assert.equal(v.frames.length,2);assert.equal(v.outcome.modeledReturn,0);assert.equal(v.outcome.termination,'STOP')}else{assert.equal(v.frames.length,29);assert.deepEqual(v.episode.history.map(a=>a.interaction_mode),['aspirate','probe']);assert.equal(v.outcome.totalRemovedMm3,1);assert.equal(v.outcome.completePathMm,6);assert(Math.abs(v.outcome.modeledReturn-.704)<1e-12);assert.equal(v.outcome.contactedAndRetained,true);assert.equal(v.outcome.termination,'horizon');assert(v.frames.some(frame=>frame.recordedTool?.tipRasMm.some(n=>!Number.isInteger(n))));}}});
for(const[name,mutate]of[
 ['goal coordinate',e=>e.publicGoal.rasMm[0]+=.25],
 ['crop frame',e=>e.initialObservationBinding.cropAffine[0][3]+=.25],
 ['channel availability',e=>e.initialObservationBinding.channelAvailable[4]=true],
 ['coverage identity',e=>e.initialObservationBinding.channelCoverageHashes[4]=e.initialObservationBinding.channelCoverageHashes[0]],
 ['exact withdrawal pose',e=>e.replayFrames.find(f=>f.phase==='withdrawal').tipRasMm[0]+=.25],
 ['contact treated as removal',e=>{const f=e.replayFrames.find(f=>f.mode==='probe'&&f.contactIndicesNative.length);f.removedIndicesNative=f.contactIndicesNative}],
 ['macro contact/reward laundering',e=>{const a=e.history.find(a=>a.interaction_mode==='probe');a.probe_contact_indices_native=[];a.goal_potential_after=0;a.reward-=1;for(const rows of [e.planning.strategy.history,e.metrics.history]){const r=rows.find(a=>a.interaction_mode==='probe');r.probe_contact_indices_native=[];r.goal_potential_after=0;r.reward-=1}e.metrics.total_reward-=1}]
])test(`re-sealed saved family refuses ${name}`,async()=>{const f=familyFixture();mutate(f.result.episode);resealFamily(f.result);await assert.rejects(check(f));});
test('unavailable trained label and private transfer refuse before reading source assets',async()=>{for(const mutate of [f=>f.result.episode.selector='IL',f=>f.result.case.metadata.privateReference={path:'/private',dtype:'uint8',byteLength:1,shape:[1]}]){const f=familyFixture();mutate(f);resealFamily(f.result);await assert.rejects(hydrateContactFamilyEpisode(f.result,{readAsset:()=>assert.fail('before source asset read')},familyRequest(f),familyCatalog()));assert.throws(()=>validateFamilyResult(f.result,familyRequest(f),familyCatalog()));}});
test('changed generated source bytes cannot be substituted behind the original transfer identity',async()=>{const f=familyFixture(),id=f.result.case.mri.assetId,bytes=Buffer.from(f.assets[id],'base64');bytes[0]^=1;f.assets[id]=bytes.toString('base64');await assert.rejects(check(f),/checksum|integrity|digest/i);});

test('time-cap response is refused before any asset and cannot be shown as STOP',async()=>{const f=familyFixture();f.result.episode.planning.time_cap_reached=true;resealFamily(f.result);await assert.rejects(hydrateContactFamilyEpisode(f.result,{readAsset:()=>assert.fail('time cap before assets')},familyRequest(f),familyCatalog()),/time limit/);});
