import assert from 'node:assert/strict';import{before,after,test}from'node:test';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';import{createServer}from'vite';import React from'react';import{renderToStaticMarkup}from'react-dom/server';import{familyFixture,familyCatalog,familyRequest,familyAssets}from'./helpers/contact-family-fixture.mjs';
let server,cache,Panel,stop,search;
before(async()=>{cache=await fs.mkdtemp(path.join(os.tmpdir(),'contact-family-panel-'));server=await createServer({root:fileURLToPath(new URL('../',import.meta.url)),cacheDir:cache,logLevel:'error',server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});Panel=(await server.ssrLoadModule('/src/ContactFamilyPanel.tsx')).ContactFamilyPanel;const{hydrateContactFamilyEpisode}=await server.ssrLoadModule('/src/contact-family-data.ts');for(const method of['STOP','SEARCH']){const f=familyFixture(method),view=await hydrateContactFamilyEpisode(f.result,familyAssets(f),familyRequest(f),familyCatalog());if(method==='STOP')stop=view;else search=view;}});
after(async()=>{await server?.close();if(cache)await fs.rm(cache,{recursive:true,force:true,maxRetries:3,retryDelay:50});});
const html=view=>renderToStaticMarkup(React.createElement(Panel,{api:null,view,step:view.frames.length-1,busy:false,visible:true,onExecute(){throw Error('SSR must not execute')},onStep(){},onShow(){},onSource(){},onFocusGoal(){}}));
test('genuine positive family view shows native contact/effort and public layout provenance',()=>{const text=html(search);for(const expected of['pcf-10','TRAIN','surface','Retained and contacted','0.704','1.00 mm³','6.00 mm','0.296','Two-action limit','fixed_lattice_access_centerline_v1','No policy inference','Temporary episode','Motor and language channels are unavailable'])assert(text.includes(expected),expected);assert(!text.includes('Target removed'));assert(!text.includes('Final learned policy · live owned inference'));assert(!text.includes('Evaluate vessel'));});
test('genuine STOP is visibly a terminal zero outcome and capped SEARCH qualification is separate from native replay',()=>{let text=html(stop);assert(text.includes('STOP · committed terminal action'));assert(text.includes('Retained · not contacted'));assert(text.includes('0.000'));const capped={...search,episode:{...search.episode,planning:{...search.episode.planning,call_cap_reached:true}}};text=html(capped);assert(text.includes('Search was incomplete'));assert(text.includes('call limit'));assert(text.includes('0.704'));assert(!text.includes('Failed'));});

test('defensive panel names a time cap; v3 admission remains responsible for refusing it',()=>{const invalid={...search,episode:{...search.episode,planning:{...search.episode.planning,time_cap_reached:true}}};assert(html(invalid).includes('time limit'));});
