import assert from 'node:assert/strict';
import {test} from 'node:test';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import {requirePersistableContact} from '../src/public-contact-data.ts';
const source=fs.readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');
function block(name,next){const start=source.indexOf(`  const ${name} =`),end=source.indexOf(next,start);assert(start>=0&&end>start);return stripTypeScriptTypes(source.slice(start,end));}
const request={fixture:'generated-public-contact-family-v2',layoutId:'pcf-00',goalId:'surface',selector:'SEARCH'};
function driver(call,hydrate){
 const events=[],old={label:'old actor'},view={source:{caseHash:'family-case'},episode:{publicGoal:{rasMm:[4.5,7.25,3]}}};
 const context={api:{executePublicContactFamilyEpisode:call},controlsBlocked:false,readonly:false,episodeGeneration:{current:0},caseGeneration:{current:4},mounted:{current:true},hydrateContactFamilyEpisode:hydrate??(async()=>view),installCase:async()=>{events.push('installed');context.caseGeneration.current++;context.actor=null;context.contact=null;return true},setEpisodePending:v=>events.push(['pending',v]),setError(){},setEpisodeVisible:v=>events.push(['visible',v]),setFamilyView:v=>context.family=v,setFamilyStep:v=>events.push(['step',v]),setEpisodeWorkflow:v=>events.push(['workflow',v]),setCursor:v=>events.push(['cursor',v]),setCameraMode(){},setPlanningTab(){},setMessage(){},reportError:e=>events.push(['error',e.message]),actor:old,contact:{},family:null};
 vm.runInNewContext(block('executeFamily','  const executeContact')+'\nglobalThis.execute=executeFamily;',context);
 return{context,events,view,old};
}
test('actual App uses family DTO and separately installs checked family after old actor/contact replacement',async()=>{let sent;const d=driver(async r=>{sent=r;return{}});await d.context.execute(request,{});assert.equal(sent,request);assert.equal(d.context.actor,null);assert.equal(d.context.contact,null);assert.equal(d.context.family,d.view);assert(d.events.some(v=>Array.isArray(v)&&v[0]==='workflow'&&v[1]==='contact-family'));assert.deepEqual(Array.from(d.events.find(v=>Array.isArray(v)&&v[0]==='cursor')[1]),[4.5,7.25,3]);});
test('late family response after source replacement cannot install or revive the prior actor',async()=>{let release;const d=driver(()=>new Promise(r=>release=r)),pending=d.context.execute(request,{});d.context.caseGeneration.current++;release({});await pending;assert.equal(d.context.actor,d.old);assert.equal(d.context.family,null);assert(!d.events.includes('installed'));});
test('late family response after unmount cannot publish a view',async()=>{let release;const d=driver(()=>new Promise(r=>release=r)),pending=d.context.execute(request,{});d.context.mounted.current=false;release({});await pending;assert.equal(d.context.family,null);assert(!d.events.includes('installed'));});
for(const phase of ['request','validation'])test(`${phase} failure does not become STOP or install an unverified view`,async()=>{const fail=async()=>{throw Error('UNAVAILABLE_OR_INVALID')},d=driver(phase==='request'?fail:async()=>({}),phase==='validation'?fail:undefined);await d.context.execute(request,{});assert.equal(d.context.actor,d.old);assert.equal(d.context.family,null);assert(!d.events.includes('installed'));assert(d.events.some(v=>Array.isArray(v)&&v[0]==='error'&&v[1]==='UNAVAILABLE_OR_INVALID'));});
test('temporary family prevents actual Save before API in every workflow',async()=>{let calls=0;const c={api:{saveCase:async()=>calls++},payload:{caseHash:'family'},act:f=>f(),publicContactView:null,familyView:{},requirePersistableContact,requirePersistableEpisode:()=>assert.fail('family refusal must be first')};vm.runInNewContext(block('save','  useEffect(() => {')+'\nglobalThis.saveAction=save;',c);await assert.rejects(c.saveAction(),/not saved/);assert.equal(calls,0);});
test('ordinary reopen clears family state and restores saved actor workflow and position',async()=>{const code=block('installCase','  const showEpisode'),calls={diagnosticClears:0},actor={episode:{selector:'RL256_ASPIRATION_TRANSFER'}},reopened={source:{caseHash:'same',metadata:{is_synthetic:true}},volume:{compartments:[]},episodeView:actor,episodeStep:7,episodeVisible:true,series:[],imagingState:null};const c={useCallback:f=>f,caseGeneration:{current:0},activeCaseHash:{current:'same'},mounted:{current:true},imaging:{invalidate(){},restore(){}},diagnostic:{clear(){calls.diagnosticClears++}},hydrateWorkspace:async()=>{assert.equal(calls.diagnosticClears,1,'diagnostics must clear before reopen hydration');return reopened},clearPrior(){},clearProposal(){},resetDisplayToPrimary(){},initialCursor:()=>[0,0,0],rasPoint:v=>v};for(const match of code.matchAll(/\b(set[A-Z]\w*)\(/g))c[match[1]]=v=>calls[match[1]]=v;vm.runInNewContext(code+'\nglobalThis.install=installCase;',c);assert.equal(await c.install(reopened.source,{}),true);assert.equal(calls.diagnosticClears,1);assert.equal(calls.setFamilyView,null);assert.equal(calls.setFamilyStep,0);assert.equal(calls.setEpisodeWorkflow,'aspiration');assert.equal(calls.setEpisodeView,actor);assert.equal(calls.setEpisodeStep,7);});
test('family step/show restores primary source and never calls actor comparison or vascular API',()=>{const events=[],c={familyView:{source:{caseHash:'same'},frames:[{},{}]},activeCaseHash:{current:'same'},setEpisodeWorkflow:v=>events.push(v),resetDisplayToPrimary:()=>events.push('primary'),inspection:{invalidate(){}},clearPrior(){},clearProposal(){},setCertifiedReplay(){},setEpisodeVisible(){},setCameraMode(){},setFamilyStep:v=>events.push(v)};vm.runInNewContext(block('showFamily','  const executeFamily')+'\nglobalThis.step=requestFamilyStep;',c);c.step(1);assert.deepEqual(events,[1,'contact-family','primary']);c.step(1.5);assert.equal(events.length,3);});
