import assert from 'node:assert/strict';import {before,after,test}from'node:test';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';import{createServer}from'vite';import React from'react';import{renderToStaticMarkup}from'react-dom/server';import{fixture}from'./vascular-fixture.mjs';
let server,cache,Readout,Panel;
before(async()=>{cache=await fs.mkdtemp(path.join(os.tmpdir(),'vascular-panel-'));server=await createServer({root:fileURLToPath(new URL('../',import.meta.url)),cacheDir:cache,logLevel:'error',server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});const module=await server.ssrLoadModule('/src/EpisodeVascularPanel.tsx');Readout=module.EpisodeVascularReadout;Panel=module.EpisodeVascularPanel;});
after(async()=>{await server?.close();if(cache)await fs.rm(cache,{recursive:true,force:true});});
const html=(index)=>renderToStaticMarkup(React.createElement(Readout,{evaluation:fixture().result.evaluation,actionIndex:index}));
test('active action shows separate shaft unknown, tip positive and full-tool outcomes for complete recorded path',()=>{const text=html(0);for(const expected of ['Action 1','Shaft','Tip','Full tool','Annotated encounter','Unknown where coverage is absent','outside reference field of view','not instantaneous contact','Planning did not use these annotations'])assert(text.includes(expected),expected);assert(!text.includes('Action 2'));});
test('changing same replay action index changes the bound action readout and does not borrow earlier positive contact',()=>{const text=html(1);assert(text.includes('Action 2'));assert(text.includes('Probe'));assert(!text.includes('Annotated encounter'));assert(text.includes('0 positive annotation cells'));});
test('initial and STOP do not invent a contact sweep or negative vascular clearance',()=>{assert(html(-1).includes('Initial tissue has no executed action'));const text=html(5);assert(text.includes('STOP has no tool sweep'));assert(!text.includes('positive annotation cells'));assert(text.includes('No injury probability or biological clearance'));});
test('unavailable evaluator is visible and disabled, never silently fakes a result',()=>{const {episode}=fixture();const text=renderToStaticMarkup(React.createElement(Panel,{episode,actionIndex:0,api:null,busy:false}));assert(text.includes('disabled=""'));assert(text.includes('does not provide'));assert(!text.includes('positive annotation cells'));});
