import assert from 'node:assert/strict';import {test} from 'node:test';import {createRequire} from 'node:module';
import {hydrateDevelopmentEpisode} from '../src/episode-data.ts';
import {loadEpisodeComparison,checkedEpisodeOutcome,requirePersistableEpisode} from '../src/episode-comparison-data.ts';
import {comparisonFixture,assetApi,reseal,hash} from './helpers/comparison-contract-fixture.mjs';
const require=createRequire(import.meta.url),{comparisonRequest,validateComparisonResult}=require('../electron/episode-comparison.cjs'),{episodeRequest,validateEpisodeResult}=require('../electron/development-episode.cjs');
const args=f=>({caseHash:f.result.case.caseHash,episodeId:f.result.episode.episodeId});
async function setup(){const f=comparisonFixture(),actor=await hydrateDevelopmentEpisode(f.result,assetApi(f));return{f,actor,api:{...assetApi(f),inspectDevelopmentEpisodeComparison:async request=>{assert.deepEqual(request,args(f));return f.comparison}}}}
test('same pair hydrates both complete histories and checked removal outcomes without execution',async()=>{const{f,actor,api}=await setup();validateComparisonResult(f.comparison,args(f));const v=await loadEpisodeComparison(api,actor,()=>true);assert.equal(v.companion.origin,'comparison');assert.equal(v.companion.authorship,null);assert.deepEqual(v.actorOutcome,v.searchOutcome);assert.equal(v.searchOutcome.targetRemoved,4);assert.equal(v.searchOutcome.normalRemoved,3);assert.equal(v.searchOutcome.termination,'STOP');assert.equal(v.companion.frames.length,72);assert.equal(v.companion.episode.planning.companionExecutionTransitions,2);assert.equal(v.companion.episode.planning.originalSearchModelTransitionCalls,14);assert.throws(()=>requirePersistableEpisode(v.companion),/Return to the actor/);assert.doesNotThrow(()=>requirePersistableEpisode(actor));});
test('companion is output-only and cannot enter ordinary execute or imported episode paths',async()=>{const f=comparisonFixture();assert.throws(()=>episodeRequest({fixture:'generated-sequential-v1',selector:'RL256_ASPIRATION_MATCHED_SEARCH'}));assert.throws(()=>validateEpisodeResult({case:f.result.case,...f.comparison.companion},{selector:'RL256_ASPIRATION_MATCHED_SEARCH'}));for(const origin of ['live','reopened'])await assert.rejects(hydrateDevelopmentEpisode({case:f.result.case,...f.comparison.companion},{readAsset:()=>assert.fail('asset before origin check')},origin));});
test('identity-only request refuses renderer pair, path and episode injection',()=>{const f=comparisonFixture();assert.deepEqual(comparisonRequest(args(f)),args(f));for(const key of ['pair','episode','checkpoint','path'])assert.throws(()=>comparisonRequest({...args(f),[key]:{}}));});
for(const[name,change]of[
 ['pair',f=>f.comparison.pairSeal=hash('2')],['actor seal',f=>f.comparison.actorStrategySeal=hash('2')],['source root',f=>f.comparison.companion.episode.sourceBinding.structural_intensity_hash=hash('2')],
 ['tool registry',f=>f.comparison.companion.episode.tools[0].shaft_radius_mm+=.1],['projected root',f=>f.comparison.initialProjectedObservationHash=hash('2')],
 ['probe',f=>f.comparison.companion.episode.history[0].interaction_mode='probe'],['forward',f=>f.comparison.companion.episode.planning.actorForwardCalls=1],
 ['execution count',f=>f.comparison.companion.episode.planning.companionExecutionTransitions=14],['accounting',f=>f.comparison.companion.episode.planning.searchAccounting.model_transition_calls=99],
 ['extra private field',f=>f.comparison.privateMask={assetId:'private'}],['nested asset',f=>f.comparison.companion.episode.planning.unexpected={path:'/private',dtype:'uint8',byteLength:1}]
])test(`resealed ${name} cannot replace current pair before assets`,async()=>{const{f,actor,api}=await setup();change(f);reseal(f.comparison.companion);await assert.rejects(loadEpisodeComparison({...api,readAsset:()=>assert.fail('asset before pair/authority check')},actor,()=>true));});
test('resealed withdrawal motion still fails the full recorded native path check',async()=>{const{f,actor,api}=await setup();f.comparison.companion.episode.replayFrames.find(r=>r.phase==='withdrawal').tipRasMm[0]++;reseal(f.comparison.companion);await assert.rejects(loadEpisodeComparison(api,actor,()=>true),/exact committed/);});
test('inconsistent finite outcome cannot be shown beside checked masks',async()=>{const{f,actor,api}=await setup();f.comparison.companion.episode.metrics.target_removed_mm3++;reseal(f.comparison.companion);await assert.rejects(loadEpisodeComparison(api,actor,()=>true),/outcome differs/);actor.episode.metrics.total_reward=NaN;assert.throws(()=>checkedEpisodeOutcome(actor),/nonfinite/);});
test('late response and actor alias mutation leave the original view untouched',async()=>{for(const mutate of [false,true]){const{f,actor,api}=await setup();let current=true;const call=async()=>{if(mutate)actor.episode.initialStateId=hash('3');else current=false;return f.comparison};await assert.rejects(loadEpisodeComparison({...api,inspectDevelopmentEpisodeComparison:call},actor,()=>current),mutate?/mutated/:/newer episode/);assert.equal(actor.origin,'live');}});
test('reopened attribution cannot request a missing live pair',async()=>{const{actor}=await setup();actor.origin='reopened';await assert.rejects(loadEpisodeComparison({inspectDevelopmentEpisodeComparison:()=>assert.fail('request')},actor,()=>true),/retained live actor/);});
