import assert from 'node:assert/strict';import {test} from 'node:test';import {createHash} from 'node:crypto';
import {checkedVascularEvaluation,loadVascularEvaluation} from '../src/episode-vascular-data.ts';import {fixture,reseal} from './vascular-fixture.mjs';
test('separate scalar evaluation preserves full episode and original ordinal-to-action mapping',async()=>{const {episode,result}=fixture(),before=structuredClone(episode);const e=await checkedVascularEvaluation(result,episode);assert.deepEqual(episode,before);assert.equal(e.perAction.length,6);assert.equal(e.perAction.at(-1).sweepCount,0);assert.equal(e.perAction.at(-1).wholeTool,null);assert.equal(e.perAction[0].shaft.annotated_positive_encounter,null);assert.equal(e.perAction[0].tip.annotated_positive_encounter,true);});
for(const [name,change] of [
 ['episode identity',e=>e.episodeId='sha256:'+'a'.repeat(64)],['source identity',e=>e.sourceHash='sha256:'+'a'.repeat(64)],['strategy seal',e=>e.strategySeal='sha256:'+'a'.repeat(64)],
 ['action order',e=>e.perAction.reverse()],['action ID',e=>e.actionIds[0]='other'],['STOP sweep',e=>e.perAction.at(-1).sweepCount=1],
 ['unknown made negative',e=>e.perAction[0].shaft.annotated_positive_encounter=false],['outside made complete',e=>e.perAction[0].shaft.annotation_coverage_complete_for_sweep=true],
 ['injury claim',e=>e.clinicalInjuryProbability=0.1],['vessel-free claim',e=>e.wholeTool.biological_vessel_free=true],['removed overlap',e=>e.removedOverlap.outcomes={volume:1}],
])test(`resealed ${name} cannot impersonate current replay`,async()=>{const {episode,result}=fixture();change(result.evaluation);reseal(result);await assert.rejects(checkedVascularEvaluation(result,episode));});
test('resealed physical-history pose still differs from authoritative episode',async()=>{const {episode,result}=fixture(),h=JSON.parse(result.evaluation.physicalHistoryCanonicalJson);h[0].microsteps[0].tip_end_mm[0]++;result.evaluation.physicalHistoryCanonicalJson=JSON.stringify(h);result.evaluation.physicalHistoryHash='sha256:'+createHash('sha256').update(result.evaluation.physicalHistoryCanonicalJson).digest('hex');reseal(result);await assert.rejects(checkedVascularEvaluation(result,episode),/physical history/)});
test('late response for a replaced episode is withheld before install',async()=>{const {episode,result}=fixture();let active=true,resolve,called;const began=new Promise(r=>called=r);const pending=loadVascularEvaluation({evaluateDevelopmentEpisodeVascular:async args=>{assert.deepEqual(args,{caseHash:episode.caseHash,episodeId:episode.episodeId});called();return new Promise(r=>resolve=r)}},episode,()=>active);await began;active=false;resolve(result);await assert.rejects(pending,{name:'AbortError'});});
test('request holds a detached expected episode across await',async()=>{const {episode,result}=fixture();const e=await loadVascularEvaluation({evaluateDevelopmentEpisodeVascular:async()=>{episode.history[0].action_id='mutated';return result}},episode,()=>true);assert.notEqual(e.actionIds[0],episode.history[0].action_id)});
