import assert from 'node:assert/strict';import {test} from 'node:test';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
// Tiny deterministic hook driver: effects/cleanup and rerenders are explicit.
function driver(loader){const state=[],effects=[],refs=[];let si=0,ei=0,ri=0,queued=[];const same=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>v===b[i]);
 const hooks={useState(initial){const i=si++;if(!(i in state))state[i]=initial;return[state[i],v=>{state[i]=typeof v==='function'?v(state[i]):v}]},useRef(initial){const i=ri++;return refs[i]??(refs[i]={current:initial})},useEffect(create,deps){const i=ei++;if(!same(effects[i]?.deps,deps)){queued.push(()=>{effects[i]?.cleanup?.();effects[i]={deps,cleanup:create()}})}}};
 let code=stripTypeScriptTypes(fs.readFileSync(new URL('../src/use-episode-comparison.ts',import.meta.url),'utf8')).replace(/^import .*;$/mg,'').replace('export function useEpisodeComparison','function useEpisodeComparison');const context={...hooks,loadEpisodeComparison:loader,Error};vm.runInNewContext(code+'\nglobalThis.hook=useEpisodeComparison;',context);
 return{render(...args){si=ei=ri=0;let value=context.hook(...args);if(queued.length){const pending=queued;queued=[];pending.forEach(f=>f());si=ei=ri=0;value=context.hook(...args)}return value},unmount(){effects.forEach(e=>e.cleanup?.())}};
}
const actor=()=>({origin:'live',episode:{selector:'RL256_ASPIRATION_TRANSFER'},source:{caseHash:'case'},frames:[0,1,2]});
test('branch selection keeps actor frame storage untouched and resets only companion cursor',async()=>{const a=actor(),c={origin:'comparison',frames:[0,1,2,3]},d=driver(async()=>({actor:a,companion:c}));let h=d.render(a,{},true,'case');await h.inspect();h=d.render(a,{},true,'case');assert.equal(h.activeView,a);h.select('search');h=d.render(a,{},true,'case');assert.equal(h.activeView,c);h.setStep(3);h=d.render(a,{},true,'case');assert.equal(h.companionStep,3);h.setStep(4);h=d.render(a,{},true,'case');assert.equal(h.companionStep,3);h.select('actor');h=d.render(a,{},true,'case');assert.equal(h.activeView,a);assert.deepEqual(a.frames,[0,1,2]);assert.equal(h.companionStep,0);});
test('replacing same-hash actor or changing case discards late companion',async()=>{for(const changedCase of [false,true]){const a=actor();let release,valid;const d=driver(async(_api,_actor,check)=>{valid=check;return new Promise(r=>release=r)});let h=d.render(a,{},true,'case');const pending=h.inspect();h=d.render(changedCase?a:actor(),{},true,changedCase?'different':'case');assert.equal(valid(),false);release({actor:a,companion:{frames:[0,1]}});await pending;h=d.render(changedCase?a:actor(),{},true,changedCase?'different':'case');assert.equal(h.result,null);assert.equal(h.arm,'actor');}});
test('load failure keeps actor view and error distinct from STOP',async()=>{const a=actor(),d=driver(async()=>{throw Error('COMPARISON_UNAVAILABLE')});let h=d.render(a,{},true,'case');await h.inspect();h=d.render(a,{},true,'case');assert.equal(h.activeView,a);assert.equal(h.result,null);assert.equal(h.error,'COMPARISON_UNAVAILABLE');assert.equal(h.pending,false);});
test('unmount invalidates pending publication',async()=>{const a=actor();let valid,release;const d=driver(async(_api,_actor,check)=>{valid=check;return new Promise(r=>release=r)});const pending=d.render(a,{},true,'case').inspect();d.unmount();assert.equal(valid(),false);release({actor:a,companion:{frames:[]}});await pending;});
