import assert from'node:assert/strict';import{test}from'node:test';import fs from'node:fs';import vm from'node:vm';import{stripTypeScriptTypes}from'node:module';
import{requirePersistableContact}from'../src/public-contact-data.ts';
const source=fs.readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');
function functionText(name,next){const start=source.indexOf(`  const ${name} =`),end=source.indexOf(next,start);assert(start>=0&&end>start);return stripTypeScriptTypes(source.slice(start,end));}
function executeDriver(apiCall){const events=[],existing={label:'old-actor'},view={source:{caseHash:'case'},episode:{publicGoal:{rasMm:[6,6,3]}}};const context={api:{executePublicSurfaceContactEpisode:apiCall},controlsBlocked:false,readonly:false,contactGoal:'near',contactSelector:'scripted',episodeGeneration:{current:0},caseGeneration:{current:5},mounted:{current:true},hydratePublicContactEpisode:async()=>view,installCase:async()=>{events.push('installed');context.caseGeneration.current++;context.actor=null;return true},setEpisodePending:v=>events.push(['pending',v]),setError:()=>{},setEpisodeVisible:v=>events.push(['visible',v]),setPublicContactView:v=>{context.contact=v},setContactStep:v=>events.push(['step',v]),setEpisodeWorkflow:v=>events.push(['workflow',v]),setCursor:v=>events.push(['cursor',v]),setCameraMode:()=>{},setPlanningTab:()=>{},setMessage:()=>{},reportError:e=>events.push(['error',e.message]),actor:existing,contact:null};vm.runInNewContext(functionText('executeContact','  const executeEpisode')+'\nglobalThis.execute=executeContact;',context);return{context,events,view,existing};}
test('actual App contact command uses fixed DTO and installs a separate view after old actor replacement',async()=>{let request;const d=executeDriver(async r=>{request=r;return {}});await d.context.execute();assert.deepEqual(JSON.parse(JSON.stringify(request)),{fixture:'generated-public-surface-contact-v1',goalId:'near',selector:'scripted'});assert.equal(d.context.actor,null);assert.equal(d.context.contact,d.view);assert(d.events.some(e=>Array.isArray(e)&&e[0]==='cursor'));assert.deepEqual(d.events.at(-1),['pending',false]);});
test('actual App discards late contact response after a source change',async()=>{let release;const d=executeDriver(()=>new Promise(r=>release=r)),pending=d.context.execute();d.context.caseGeneration.current++;release({});await pending;assert.equal(d.context.actor,d.existing);assert.equal(d.context.contact,null);assert(!d.events.includes('installed'));});
test('failed contact command never installs STOP or substitutes a new result',async()=>{const d=executeDriver(async()=>{throw Error('CANCELLED_OR_FAILED')});await d.context.execute();assert.equal(d.context.actor,d.existing);assert.equal(d.context.contact,null);assert(d.events.some(e=>Array.isArray(e)&&e[0]==='error'&&e[1]==='CANCELLED_OR_FAILED'));});
test('actual Save guard rejects contact before API even when another workflow tab is selected',async()=>{let calls=0;const context={api:{saveCase:async()=>{calls++}},payload:{caseHash:'case'},act:fn=>fn(),publicContactView:{},requirePersistableContact,requirePersistableEpisode:()=>assert.fail('contact guard must be first')};const text=functionText('save','  useEffect(() => {');vm.runInNewContext(text+'\nglobalThis.saveAction=save;',context);await assert.rejects(context.saveAction(),/not saved/);assert.equal(calls,0);});
test('actual ordinary reopen clears contact and restores aspiration workflow and saved actor frame',async()=>{
 const code=functionText('installCase','  const showEpisode'),calls={diagnosticClears:0},actor={episode:{selector:'RL256_ASPIRATION_TRANSFER'}};
 const reopened={source:{caseHash:'same-case',metadata:{is_synthetic:true}},volume:{compartments:[]},episodeView:actor,episodeStep:7,episodeVisible:true,series:[],imagingState:null};
 const context={useCallback:f=>f,caseGeneration:{current:0},activeCaseHash:{current:'same-case'},mounted:{current:true},imaging:{invalidate(){},restore(){}},diagnostic:{clear(){calls.diagnosticClears++}},hydrateWorkspace:async()=>{assert.equal(calls.diagnosticClears,1,'diagnostics must clear before reopen hydration');return reopened},clearPrior(){},clearProposal(){},resetDisplayToPrimary(){},initialCursor:()=>[0,0,0],rasPoint:v=>v};
 for(const name of code.matchAll(/\b(set[A-Z]\w*)\(/g))context[name[1]]=v=>{calls[name[1]]=v};
 vm.runInNewContext(code+'\nglobalThis.install=installCase;',context);assert.equal(await context.install(reopened.source,{}),true);
 assert.equal(calls.diagnosticClears,1);assert.equal(calls.setPublicContactView,null);assert.equal(calls.setContactStep,0);assert.equal(calls.setEpisodeWorkflow,'aspiration');assert.equal(calls.setEpisodeView,actor);assert.equal(calls.setEpisodeStep,7);assert.equal(calls.setEpisodeVisible,true);
});
test('actual imported actor step/show restores aspiration workflow and primary source view',()=>{
 const calls=[],context={displayedEpisodeView:{source:{caseHash:'same'},frames:[{},{}]},activeCaseHash:{current:'same'},comparison:{arm:'actor'},resetDisplayToPrimary:()=>calls.push('primary'),inspection:{invalidate(){}},clearPrior(){},clearProposal(){},setCertifiedReplay(){},setEpisodeVisible:v=>calls.push(['visible',v]),setEpisodeWorkflow:v=>calls.push(['workflow',v]),setCameraMode(){},setMessage(){},setEpisodeStep:v=>calls.push(['step',v])};
 vm.runInNewContext(functionText('showEpisode','  const selectComparisonArm')+'\nglobalThis.step=requestEpisodeStep;',context);context.step(1);
 assert(calls.some(v=>Array.isArray(v)&&v[0]==='workflow'&&v[1]==='aspiration'));assert(calls.includes('primary'));assert(calls.some(v=>Array.isArray(v)&&v[0]==='step'&&v[1]===1));
});
