import assert from'node:assert/strict';import{before,after,test}from'node:test';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';import{createServer}from'vite';import React from'react';import{renderToStaticMarkup}from'react-dom/server';import{contactFixture,assetApi}from'./helpers/public-contact-fixture.mjs';
let server,cache,Panel,near,costly;
before(async()=>{cache=await fs.mkdtemp(path.join(os.tmpdir(),'public-contact-panel-'));server=await createServer({root:fileURLToPath(new URL('../',import.meta.url)),cacheDir:cache,logLevel:'error',server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});Panel=(await server.ssrLoadModule('/src/PublicContactPanel.tsx')).PublicContactPanel;const{hydratePublicContactEpisode}=await server.ssrLoadModule('/src/public-contact-data.ts');let f=contactFixture();near=await hydratePublicContactEpisode(f.result,assetApi(f));f=contactFixture('costly-SEARCH');costly=await hydratePublicContactEpisode(f.result,assetApi(f));});
after(async()=>{await server?.close();if(cache)await fs.rm(cache,{recursive:true,force:true,maxRetries:3,retryDelay:50});});
const props=(extra={})=>({view:null,step:0,selector:'scripted',goalId:'near',busy:false,visible:false,onSelector:()=>{},onGoal:()=>{},onExecute:()=>{},onStep:()=>{},onShow:()=>{},onSource:()=>{},onFocusGoal:()=>{},...extra});const html=p=>renderToStaticMarkup(React.createElement(Panel,props(p)));const nodes=e=>!e||typeof e!=='object'?[]:[e,...React.Children.toArray(e.props?.children).flatMap(nodes)];
test('two public goals and only scripted/SEARCH selectors change selection without executing',()=>{const calls=[],tree=Panel(props({onSelector:v=>calls.push(v),onGoal:v=>calls.push(v),onExecute:()=>calls.push('execute')})),selects=nodes(tree).filter(n=>n.type==='select');assert.deepEqual(nodes(selects[0]).filter(n=>n.type==='option').map(n=>n.props.value),['near','costly']);assert.deepEqual(nodes(selects[1]).filter(n=>n.type==='option').map(n=>n.props.value),['scripted','SEARCH']);selects[0].props.onChange({target:{value:'costly'}});selects[1].props.onChange({target:{value:'SEARCH'}});assert.deepEqual(calls,['costly','SEARCH']);});
test('checked public metrics are separate from nominal-target background and private evidence',()=>{const text=html({view:near,step:near.frames.length-1});for(const value of ['Retained and contacted','0.708','1.00 mm³','2.00 mm','0.292','Two-action limit','earns no reward here','fixture background','not an anatomical label','temporary','No private-reference scoring','No learned policy'])assert(text.includes(value),value);assert(!text.includes('Target removed'));assert(!text.includes('Trained transfer'));assert(!text.includes('Evaluate vessel'));});
test('STOP outcome remains explicit zero contact, not a failed request',()=>{const text=html({view:costly,step:1,selector:'SEARCH',goalId:'costly'});assert(text.includes('STOP · committed terminal action'));assert(text.includes('Retained · not yet contacted'));assert(text.includes('0.000'));assert(!text.includes('Retained and contacted'));});
test('goal focus and timeline use real checked replay controls',()=>{const calls=[],tree=Panel(props({view:near,onFocusGoal:()=>calls.push('goal'),onStep:v=>calls.push(v)}));nodes(tree).find(n=>n.type==='button'&&n.props.children==='Focus public goal').props.onClick();const timeline=nodes(tree).find(n=>n.type==='ol');nodes(timeline).filter(n=>n.type==='button')[1].props.onClick();assert.deepEqual(calls,['goal',near.episode.replayFrames.findIndex(f=>f.actionIndex===1)]);});
