import assert from 'node:assert/strict';import {test}from'node:test';import {checkedPublicGoal,publicGoalSlicePoint}from'./publicGoal.ts';import {slicePoint,sliceRect,volumeBounds}from'./coordinates.ts';
const hash='sha256:'+'a'.repeat(64),volume={caseHash:hash,shape:[13,13,12],affine:[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],frame:'RAS+'};
const goal=()=>({scope:'declared-public-geometric-goal',caseHash:hash,episodeId:hash,objectiveHash:hash,nativeIndex:[6,6,3],rasMm:[6,6,3],state:'retained-uncontacted'});
test('goal location is detached and native/RAS bound, independently of cursor',()=>{const g=goal(),v=checkedPublicGoal(volume,g);g.rasMm[0]++;assert.deepEqual(v.rasMm,[6,6,3]);for(const change of [g=>g.caseHash='other',g=>g.rasMm[2]++,g=>g.nativeIndex[2]=13,g=>g.state='vessel-free']){const g=goal();change(g);assert.throws(()=>checkedPublicGoal(volume,g));}});
test('goal glyph meets the same native location in all linked slice coordinate maps',()=>{const g=goal(),bounds=volumeBounds(volume.shape,volume.affine);for(const plane of ['axial','coronal','sagittal']){const p=publicGoalSlicePoint(g,bounds,plane,g.rasMm,400,300);assert(p);const mapped=slicePoint(bounds,plane,g.rasMm,sliceRect(bounds,plane,400,300),p.left,p.top);assert(mapped.every((v,i)=>Math.abs(v-g.rasMm[i])<1e-10));}assert.equal(publicGoalSlicePoint(g,bounds,'axial',[6,6,4],400,300),null);});
import fs from'node:fs';import vm from'node:vm';import{stripTypeScriptTypes}from'node:module';import*as THREE from'three';import{PUBLIC_GOAL_COLOR}from'./publicGoal.ts';
test('actual renderer marker is at declared RAS and disposes on replacement and clear',()=>{
 const source=fs.readFileSync(new URL('./VolumeRenderer.ts',import.meta.url),'utf8'),start=source.indexOf('  setPublicGoal('),end=source.indexOf('\n  /**',start),dispose=source.slice(source.indexOf('function disposeObject('),source.indexOf('\nfunction dataTexture('));
 const context={THREE,checkedPublicGoal,PUBLIC_GOAL_COLOR};vm.runInNewContext(stripTypeScriptTypes(dispose+'\nclass Marker {\n'+source.slice(start,end)+'\n}\nglobalThis.Marker=Marker;'),context);
 const object=new context.Marker();object.volume=volume;object.publicGoalObject=new THREE.Group();object.requestRender=()=>{};
 object.setPublicGoal(goal());const mesh=object.publicGoalObject.children[0];assert.deepEqual(mesh.position.toArray(),[6,6,3]);assert.equal(mesh.material.wireframe,true);assert.equal(mesh.material.depthTest,false);assert.equal(mesh.userData.publicGoal.scope,'declared-public-geometric-goal');let disposed=0;mesh.geometry.addEventListener('dispose',()=>disposed++);mesh.material.addEventListener('dispose',()=>disposed++);
 object.setPublicGoal({...goal(),state:'retained-contacted'});assert.equal(disposed,2);assert.equal(object.publicGoalObject.children.length,1);object.setPublicGoal(null);assert.equal(object.publicGoalObject.children.length,0);
});
