"""Tiny generated saved-result semantics and parent success/refusal controls."""
import copy, importlib.util, json, os, signal, tempfile, types, unittest
from pathlib import Path
from unittest import mock
HERE=Path(__file__).resolve().parent
L=types.ModuleType('ixi_semantics');L.__file__=str(HERE/'launch_v2.py');exec(compile((HERE/'launch_v2.py').read_bytes(),L.__file__,'exec'),L.__dict__)

class Semantics(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory(prefix='generated-semantic-',dir=HERE);self.out=Path(self.temp.name)/'attempt'
        self.release=L.candidate();self.release['archive_completion_receipt']={'path':'generated-only.json','sha256':'f'*64}
        self.release['archive_bindings']={name:{'sha256':str(i)*64} for i,name in enumerate(('IXI-T1.tar','IXI-MRA.tar','vessel_dataset.zip'))}
        self.protocol=L.child_protocol(self.release)
        for kind in ('T1','MRA'):self.protocol['selected_person']['raw_files'][kind]['size']=17
        self.report={'status':'selected_copies_and_header_qc_complete_unadmitted','person_group':'IXI:265','role':'TRAIN',
            'protocol_sha256':L.sha(L.encode(self.protocol)),'archive_completion_receipt':self.release['archive_completion_receipt'],
            'archive_read_accounting_complete':True,'other_person_member_body_bytes_read':0,'voxel_arrays_materialized':0,
            'training_admitted':False,'anatomical_registration_accepted':False,'actor_private_reference_access_added':False,
            'archive_sha256_inherited_from_transport':True,'whole_archives_rehashed_by_this_worker':False,'members':{},'member_attempts':[],
            'declared_grid_comparisons':{k:{'accepted_registration':False,'simultaneous_acquisition_established':False} for k in ('T1_to_MRA','MRA_to_derived_label')}}
        for kind,name in [('T1','IXI-T1.tar'),('MRA','IXI-MRA.tar'),('derived_vessel_label','vessel_dataset.zip')]:
            derived=kind=='derived_vessel_label';raw=None if derived else self.protocol['selected_person']['raw_files'][kind]
            self.report['member_attempts'].append({'kind':kind,'archive':name,'status':'selected_copy_and_header_complete'})
            m={'archive':name,'archive_sha256':self.release['archive_bindings'][name]['sha256'],
               'member':self.protocol['selected_person']['vessel_annotation']['member'] if derived else raw['name'],
               'source_kind':'derived_reference' if derived else 'acquired_measurement',
               'output_path':('derived_reference' if derived else 'acquired')+'/IXI265-'+kind+'.nii.gz',
               'selected_copy_rehash_verified':True,'sha256':L.sha(b'generated bytes!!'),'bytes':17,'other_member_body_bytes_read':0,'archive_bytes_read':100 if derived else 529,
               'header_qc':{'status':'header_only_inspected_no_anatomical_admission','voxel_arrays_materialized':0,'decoded_header_bytes':352,
                   'acquisition_datetime':None,'cross_modality_time_interval':None,'file_mtime_or_filename_code_interpreted_as_acquisition_time':False,
                   'extension_body_parsed':False,'gzip_footer_verified':False,'voxel_payload_length_verified':False,
                   'library_versions':{'numpy':'2.5.3','nibabel':'5.4.2'}}}
            if raw:m.update(header_sha256=raw['header_sha256'],header_offset=raw['header_offset'])
            self.report['members'][kind]=m
    def tearDown(self):self.temp.cleanup()
    def validate(self):L.semantic_success(self.report,self.protocol,L.sha(L.encode(self.protocol)),self.release)
    def test_valid_generated_report(self):self.validate()
    def test_mutated_bindings_or_scope_refuse(self):
        original=copy.deepcopy(self.report)
        for key,value in [('role','SELECT'),('training_admitted',True),('other_person_member_body_bytes_read',None),('archive_read_accounting_complete',False)]:
            self.report=copy.deepcopy(original);self.report[key]=value
            with self.assertRaises(L.Refusal):self.validate()
        self.report=copy.deepcopy(original);self.report['members']['T1']['header_sha256']='e'*64
        with self.assertRaises(L.Refusal):self.validate()
    def parent(self,signal_when=None,semantic_refusal=False):
        supervisor=L.module(L.SUPERVISOR,'generated_semantic_supervisor');io=L.module(L.IO,'generated_semantic_io')
        modules={L.SUPERVISOR:supervisor,L.IO:io,L.RSS:types.SimpleNamespace()}
        def fake_supervision(command,directory,deadline,on_start,*rest):
            intent=json.loads((directory/'intent.json').read_bytes());intent_sha=L.sha((directory/'intent.json').read_bytes())
            on_start(990011);selected=directory/'selected';selected.mkdir()
            for member in self.report['members'].values():
                p=selected/member['output_path'];p.parent.mkdir(exist_ok=True);p.write_bytes(b'generated bytes!!')
            if semantic_refusal:self.report['status']='failed_preserved_no_retry'
            (selected/'receipt.json').write_bytes(L.encode(self.report))
            (directory/'worker-terminal.json').write_bytes(L.encode({'status':'worker_adapter_complete','release_sha256':'a'*64,
                'intent_sha256':intent_sha,'worker_peak_RSS_bytes':1024,'reader_exit_code':0,'process_and_network_guard':True,'source_only_bootstrap':True}))
            if signal_when=='after_supervision':os.kill(os.getpid(),signal.SIGTERM)
            return {'supervision':'completed','worker_exit_status':0,'parent_reaped_worker':True,'worker_pid':990011}
        real_save=L.save
        def save(directory,name,value,*args):
            result=real_save(directory,name,value,*args)
            if signal_when=='during_publication' and name=='terminal.json':os.kill(os.getpid(),signal.SIGTERM)
            return result
        with mock.patch.object(L,'OUTPUT',self.out),mock.patch.object(L,'runtime_fixity',return_value=1),mock.patch.object(L,'archive_prerequisites'),mock.patch.object(L,'module',side_effect=lambda p,n:modules[p]),mock.patch.object(L,'supervise_owned',side_effect=fake_supervision),mock.patch.object(L,'save',side_effect=save),mock.patch.object(L,'child_protocol',return_value=self.protocol),mock.patch.object(L.sys,'_remind_header_verify_origins',return_value={},create=True):
            result=L.parent(self.release,Path(self.temp.name)/'generated-release.json','a'*64)
        return result,json.loads((self.out/'terminal.json').read_bytes())
    def test_parent_valid_generated_success(self):
        code,receipt=self.parent();self.assertEqual(code,0);self.assertEqual(receipt['status'],'selected_header_intake_complete_unadmitted')
    def test_exit_zero_semantic_failure(self):
        code,receipt=self.parent(semantic_refusal=True);self.assertEqual(code,1);self.assertFalse(receipt['archive_read_accounting_complete'])
    def test_success_sigterm_after_supervision_refused(self):
        code,receipt=self.parent(signal_when='after_supervision');self.assertEqual(code,1);self.assertEqual(receipt['status'],'failed_or_incomplete_no_retry')
    def test_success_sigterm_during_publication_refused(self):
        code,receipt=self.parent(signal_when='during_publication');self.assertEqual(code,1);self.assertTrue((self.out/'post-publication-refusal.json').exists())

if __name__=='__main__':unittest.main(verbosity=2)
