'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {episodeRequest,validateEpisodeResult}=require('./development-episode.cjs');
const fixture=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../tests/fixtures/development-scripted.json'),'utf8')).result;
test('exact generated request supports only explicitly named fixture and selectors',()=>{assert.deepEqual(episodeRequest({fixture:'generated-sequential-v1',selector:'SEARCH'}),{fixture:'generated-sequential-v1',selector:'SEARCH'});for(const args of [{},{fixture:'patient',selector:'scripted'},{fixture:'generated-sequential-v1',selector:'learned'},{fixture:'generated-sequential-v1',selector:'scripted',path:'/tmp/x'}])assert.throws(()=>episodeRequest(args));});
test('actual source-bound generated episode accepted before asset exposure',()=>{const result=fixture();assert.equal(validateEpisodeResult(result,{selector:'scripted'}),result);});
for(const [name,mutate] of [['tool',r=>r.episode.tools[0].working_length_mm++],['case',r=>r.case.caseHash='sha256:'+'a'.repeat(64)],['clinical',r=>r.episode.clinicalValidation=true],['selector',r=>r.episode.selector='SEARCH'],['raw serialization',r=>r.episodeCanonicalJson+=' ']])test(`main withholds changed ${name}`,()=>{const result=fixture();mutate(result);assert.throws(()=>validateEpisodeResult(result,{selector:'scripted'}));});
test('IPC is advertised, request checked in main/sidecar, response checked before asset/event forwarding',()=>{const main=fs.readFileSync(path.join(__dirname,'main.cjs'),'utf8'),sidecar=fs.readFileSync(path.join(__dirname,'sidecar.cjs'),'utf8'),preload=fs.readFileSync(path.join(__dirname,'preload.cjs'),'utf8');assert.match(main,/handle\('executeDevelopmentEpisode'.*episodeRequest/);assert.match(preload,/research:executeDevelopmentEpisode/);assert(sidecar.indexOf('validateEpisodeResult(message.result')<sidecar.indexOf('message.result = await this.assets.expose'));assert(sidecar.indexOf('validateEpisodeResult(message.result')<sidecar.indexOf("this.emit('event', { ...message"));assert.match(main,/handle\('createSyntheticCase', \(\) => engine.request\('createSyntheticCase'\)\)/);});

test('sidecar accepts display-series without expiring primary assets',async()=>{const {Sidecar}=require('./sidecar.cjs');const sent=[];const fake={closed:false,pending:new Map(),child:{stdin:{write:(s,cb)=>{sent.push(JSON.parse(s));cb?.();}}}};const result=Sidecar.prototype.request.call(fake,'importDisplaySeries',{caseHash:'case',path:'generated'},100);assert.equal(sent[0].op,'importDisplaySeries');const pending=fake.pending.get(sent[0].id);clearTimeout(pending.timeout);pending.resolve('accepted');assert.equal(await result,'accepted');});
