'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');const {vascularRequest,validateVascularResult}=require('./episode-vascular.cjs');const {Sidecar}=require('./sidecar.cjs');
const fixture=async()=>(await import('../tests/vascular-fixture.mjs')).fixture();
test('main accepts only exact episode identity selection, never supplied private inputs',()=>{const args={caseHash:'sha256:'+'a'.repeat(64),episodeId:'sha256:'+'b'.repeat(64)};assert.deepEqual(vascularRequest(args),args);for(const extra of ['episode','path','mask','reference','clinicalInjuryProbability'])assert.throws(()=>vascularRequest({...args,[extra]:null}));assert.throws(()=>vascularRequest({caseHash:'invalid',episodeId:args.episodeId}));});
test('host validates scalar result and rejects added asset before traversal/events',async()=>{const {episode,result}=await fixture(),request={caseHash:episode.caseHash,episodeId:episode.episodeId};validateVascularResult(result,request);result.evaluation.asset={path:'/forbidden',dtype:'uint8',byteLength:1};const {reseal}=await import('../tests/vascular-fixture.mjs');reseal(result);const fake={pending:new Map([['id',{op:'evaluateDevelopmentEpisodeVascular',vascularArgs:request}]]),assets:{expose:()=>assert.fail('private traversal')},emit:()=>assert.fail('event')};await assert.rejects(Sidecar.prototype.handle.call(fake,{id:'id',event:'result',result}),/fields/);});
test('sidecar advertises evaluator and preserves primary assets on accepted scalar report',async()=>{const {episode,result}=await fixture(),request={caseHash:episode.caseHash,episodeId:episode.episodeId};const sent=[],fake={closed:false,pending:new Map(),child:{stdin:{write:(data,cb)=>{sent.push(JSON.parse(data));cb?.()}}}};const response=Sidecar.prototype.request.call(fake,'evaluateDevelopmentEpisodeVascular',request,100);const record=fake.pending.get(sent[0].id);clearTimeout(record.timeout);assert.deepEqual(record.vascularArgs,request);fake.assets={clear:()=>assert.fail('cleared primary assets'),expose:async x=>x};fake.emit=()=>{};await Sidecar.prototype.handle.call(fake,{id:sent[0].id,event:'result',result});assert.equal(await response,result);});
test('actual main and preload expose only identity-selected evaluation through IPC',async()=>{
 const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
 const {episode,result}=await fixture(),handlers=new Map(),requests=[],frame={url:'file:///trusted-app.html'},window={webContents:{mainFrame:frame},isDestroyed:()=>false};
 const main=path.join(__dirname,'main.cjs'),localRequire=createRequire(main),engine={request:async(op,args)=>{requests.push([op,args]);return result}};
 const context=vm.createContext({__dirname,process,Buffer,console,__engine:engine,__window:window,__url:frame.url,require:name=>name==='electron'?{app:{requestSingleInstanceLock:()=>false,quit(){},on(){}},ipcMain:{handle:(name,callback)=>handlers.set(name,callback)}}:localRequire(name)});
 vm.runInContext(fs.readFileSync(main,'utf8'),context);vm.runInContext('engine=__engine;window=__window;allowedUrl=__url;bindOperations();',context);
 let api;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'preload.cjs'),'utf8'),{require:()=>({contextBridge:{exposeInMainWorld:(_,value)=>api=value},ipcRenderer:{invoke:(name,args)=>handlers.get(name)({sender:window.webContents,senderFrame:frame},args)}})});
 const args={caseHash:episode.caseHash,episodeId:episode.episodeId};assert.equal(await api.evaluateDevelopmentEpisodeVascular(args),result);assert.deepEqual(requests,[['evaluateDevelopmentEpisodeVascular',args]]);
 await assert.rejects(api.evaluateDevelopmentEpisodeVascular({...args,referencePath:'/private'}));assert.equal(requests.length,1);
});
