'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{Sidecar}=require('./sidecar.cjs');
const {validateComparisonResult}=require('./episode-comparison.cjs');
const fixture=async()=>(await import('../tests/helpers/comparison-contract-fixture.mjs')).comparisonFixture();
const args=f=>({caseHash:f.result.case.caseHash,episodeId:f.result.episode.episodeId});
test('sidecar preserves primary assets and exposes only accepted companion',async()=>{const f=await fixture(),sent=[],fake={closed:false,pending:new Map(),child:{stdin:{write:(data,cb)=>{sent.push(JSON.parse(data));cb?.()}}}};const response=Sidecar.prototype.request.call(fake,'inspectDevelopmentEpisodeComparison',args(f),100);const record=fake.pending.get(sent[0].id);clearTimeout(record.timeout);assert.deepEqual(record.comparisonArgs,args(f));fake.assets={clear:()=>assert.fail('primary assets cleared'),expose:async x=>x};fake.emit=()=>{};await Sidecar.prototype.handle.call(fake,{id:sent[0].id,event:'result',result:f.comparison});assert.equal(await response,f.comparison);});
test('sidecar rejects injected companion assets and re-sealed forward counts before traversal/event',async()=>{for(const bad of ['extra','forward','nested']){const f=await fixture();if(bad==='extra')f.comparison.private={path:'/forbidden'};else{if(bad==='forward')f.comparison.companion.episode.planning.actorForwardCalls=2;else f.comparison.companion.episode.planning.extra={path:'/private',dtype:'uint8',byteLength:1};(await import('../tests/helpers/comparison-contract-fixture.mjs')).reseal(f.comparison.companion)}const fake={pending:new Map([['id',{op:'inspectDevelopmentEpisodeComparison',comparisonArgs:args(f)}]]),assets:{expose:()=>assert.fail('asset exposed')},emit:()=>assert.fail('event')};await assert.rejects(Sidecar.prototype.handle.call(fake,{id:'id',event:'result',result:f.comparison}));}});
test('real main/preload method passes only identities under bounded IPC timeout',async()=>{
 const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');const f=await fixture(),handlers=new Map(),requests=[],frame={url:'file:///trusted-app.html'},window={webContents:{mainFrame:frame},isDestroyed:()=>false};
 const main=path.join(__dirname,'main.cjs'),localRequire=createRequire(main),engine={request:async(...call)=>{requests.push(call);return f.comparison}};
 const context=vm.createContext({__dirname,process,Buffer,console,__engine:engine,__window:window,__url:frame.url,require:name=>name==='electron'?{app:{requestSingleInstanceLock:()=>false,quit(){},on(){}},ipcMain:{handle:(name,callback)=>handlers.set(name,callback)}}:localRequire(name)});
 vm.runInContext(fs.readFileSync(main,'utf8'),context);vm.runInContext('engine=__engine;window=__window;allowedUrl=__url;bindOperations();',context);
 let api;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'preload.cjs'),'utf8'),{require:()=>({contextBridge:{exposeInMainWorld:(_,value)=>api=value},ipcRenderer:{invoke:(name,args)=>handlers.get(name)({sender:window.webContents,senderFrame:frame},args)}})});
 assert.equal(await api.inspectDevelopmentEpisodeComparison(args(f)),f.comparison);assert.deepEqual(requests,[['inspectDevelopmentEpisodeComparison',args(f),30000]]);
 await assert.rejects(api.inspectDevelopmentEpisodeComparison({...args(f),pair:{}}));assert.equal(requests.length,1);
});
