"""Root-owned metadata-only final freeze; no model, array or execution import.

Reuses the balanced64 freezer's conservative AST import-closure algorithm.
Both terminal TRAIN endpoints must authenticate before any output is written.
Output paths are exclusive; this freezer opens metadata and source only.
"""
import argparse
import ast
import hashlib
import json
from pathlib import Path
import subprocess
import sys

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
# Ignore any previously generated bytecode when importing these local stdlib-only
# helpers; no cache directory is created and no canonical model module is imported.
sys.dont_write_bytecode=True
sys.pycache_prefix=str(HERE/'never-written-final-freeze-pycache')
if Path(sys.pycache_prefix).exists() or Path(sys.pycache_prefix).is_symlink():
    raise FileExistsError('Fresh no-write source cache namespace required before helper imports')
sys.path.insert(0,str(HERE))
from comparison_contract import (ARMS,ENDPOINTS,TRAIN,OUTPUT,LIMITS,COHORT,COHORT_SHA,
    PUBLIC_INDEX,PUBLIC_SHA,PARENT_SECONDS,OCCUPANCY,EXPOSURE,sha,read_pinned,qualified_public,authenticate_comparison,endpoint_refs,ORIGINAL_IL,RECOVERY_INPUTS,UPSTREAM_RECOVERY_CONTRACT,UPSTREAM_RECOVERY_CONTRACT_SHA,ALLOWED_PRODUCTION_DELTA)

def relative(path):return path.relative_to(ROOT).as_posix()

def project_module(name):
    if name=='resectionlab':return ROOT/'src/resectionlab/__init__.py'
    if not name.startswith('resectionlab.'):return None
    base=ROOT/'src'/name.replace('.','/')
    if base.with_suffix('.py').is_file():return base.with_suffix('.py')
    if (base/'__init__.py').is_file():return base/'__init__.py'
    return None

def source_closure():
    """Static import closure includes lazy imports and package initializers."""
    paths={HERE/name for name in ('comparison_contract.py','select_worker.py','run_owned.py',
        'freeze-runtime.py')}
    paths.update(ROOT/'build/goal-conditioned-policy-v1'/name
        for name in ('run_contact_owned.py','darwin_fast_sampler.py'))
    paths.add(ROOT/'src/resectionlab/__init__.py')
    visited=set()
    while paths-visited:
        path=sorted(paths-visited)[0];visited.add(path)
        if path.is_symlink() or not path.is_file():raise ValueError('Regular source required: '+str(path))
        tree=ast.parse(path.read_text());in_package=path.is_relative_to(ROOT/'src/resectionlab')
        if in_package:package='.'.join(path.parent.relative_to(ROOT/'src').parts)
        for node in ast.walk(tree):
            modules=[]
            if isinstance(node,ast.Import):modules.extend(alias.name for alias in node.names)
            elif isinstance(node,ast.ImportFrom):
                if node.level and in_package:
                    base='.'.join(package.split('.')[:len(package.split('.'))-node.level+1])
                    module=base+('.'+node.module if node.module else '')
                elif node.level==0:module=node.module or ''
                else:continue
                modules.append(module)
                modules.extend(module+'.'+alias.name for alias in node.names if alias.name!='*')
            for module in modules:
                dependency=project_module(module)
                if dependency is not None:paths.add(dependency)
    return sorted(paths)

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--head',required=True)
    parser.add_argument('--rl-result-sha256',required=True,help='Exact reviewed terminal result; never read a live arm')
    args=parser.parse_args()
    def head_now():
        return subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True,timeout=5).strip()
    head=head_now()
    if head!=args.head:raise ValueError('Exact root-supplied committed HEAD required')
    output=ROOT/OUTPUT
    for path in (output,output.with_name(output.name+'.supervision'),HERE/'source-index.json',HERE/'release-template.json'):
        if path.exists() or path.is_symlink():raise FileExistsError('Final freeze/attempt path exists: '+str(path))
    endpoints={name:endpoint_refs(name,rl_result_sha256=args.rl_result_sha256) for name in ENDPOINTS}
    authenticate_comparison({'endpoints':endpoints})
    metadata={}
    def bind(ref):
        value=read_pinned(ref)
        if ref['path'] in metadata and metadata[ref['path']]!=ref['sha256']:
            raise ValueError('Conflicting metadata descriptor')
        metadata[ref['path']]=ref['sha256'];return value
    public_ref={'path':PUBLIC_INDEX,'sha256':PUBLIC_SHA};bind(public_ref)
    active,manifest,preparation_refs,preparation=qualified_public(public_ref)
    for ref in preparation_refs:bind(ref)
    cohort=bind({'path':COHORT,'sha256':COHORT_SHA})
    member=[r for r in cohort['members'] if r['subject']=='ReMIND-013']
    if (len(member)!=1 or member[0]['role']!='SELECT' or member[0]['patient_group']!='ReMIND:013'
            or manifest['source_bindings']['cohort_sha256']!=COHORT_SHA):
        raise ValueError('Original cohort and expanded SELECT013 role must agree')
    # Descriptors alone are checked. Do not stat/hash/open patient arrays here.
    for row in manifest['input_files'].values():
        path=Path(row['path'])
        if not path.is_absolute() or not path.is_relative_to(ROOT) or '..' in path.parts:
            raise ValueError('Qualified workspace public-array descriptor required')
    for refs in endpoints.values():
        original_release=bind(refs['release'])
        for key in ('result','parent','worker_final'):bind(refs[key])
        for ref in refs['contexts'].values():bind(ref)
        bind(original_release['source_index'])
    for ref in (*ORIGINAL_IL.values(),*RECOVERY_INPUTS.values()):bind(ref)
    if sha(ROOT/UPSTREAM_RECOVERY_CONTRACT)!=UPSTREAM_RECOVERY_CONTRACT_SHA:
        raise ValueError('Copied historical recovery evidence source changed')
    paths=source_closure();bindings={relative(p):sha(p) for p in paths}
    rl_release=read_pinned(endpoints['RL8']['release'])
    rl_head=rl_release['expected_head']
    changed=set(subprocess.check_output(['git','diff','--name-only',rl_head,head,'--',
        'src/resectionlab'],cwd=ROOT,text=True,timeout=5).splitlines())
    if changed!=set(ALLOWED_PRODUCTION_DELTA):
        raise ValueError('Only reviewed SELECT partial-Ds and preserved opt-in ranking sources may differ from RL')
    if any(bindings.get(path)!=digest for path,digest in ALLOWED_PRODUCTION_DELTA.items()):
        raise ValueError('Exact reviewed production bytes must be promoted before freeze')
    for path in paths:
        if path.is_relative_to(ROOT/'src'):
            committed=subprocess.check_output(['git','show',head+':'+relative(path)],cwd=ROOT,timeout=5)
            if committed!=path.read_bytes():raise ValueError('Reachable canonical source not committed: '+relative(path))
            if relative(path) not in ALLOWED_PRODUCTION_DELTA:
                old=subprocess.check_output(['git','show',rl_head+':'+relative(path)],cwd=ROOT,timeout=5)
                if old!=committed:raise ValueError('Unreviewed source delta from RL: '+relative(path))
    if any(sha(ROOT/p)!=v for p,v in bindings.items()) or any(sha(ROOT/p)!=v for p,v in metadata.items()):
        raise ValueError('Source/metadata changed during final freeze')
    if head_now()!=head:raise ValueError('HEAD changed during freeze')
    index={'version':'post-exposure-SELECT013-expanded-comparison-runtime-v1','head':head,'source_files':bindings,
        'upstream_RL_head':rl_head,'allowed_production_delta':ALLOWED_PRODUCTION_DELTA,
        'metadata_files':metadata,
        'closure_scope':'conservative repository Python import closure including lazy imports; external runtime is recorded by owned execution',
        'scope':'public013 only; held037 remains denominator2; no arrays or checkpoint payload read in freeze'}
    release={'status':'pending_root_release','expected_head':head,'output':OUTPUT,
        'arms':list(ARMS),'endpoints':endpoints,'occupancy_condition':OCCUPANCY,'post_exposure_condition':EXPOSURE,
        'public_index':{'path':PUBLIC_INDEX,'sha256':PUBLIC_SHA},
        'partial_domain_inputs':True,'public_preparation':preparation,
        'limits':LIMITS,'parent_seconds':PARENT_SECONDS,'greedy_seconds':60,
        'attempts':1,'automatic_retry':False,'planned_SELECT_denominator':2,
        'held_cases':['ReMIND-037'],'EVAL_closed':True,
        'selection_rule':'two predetermined frozen matched TRAIN endpoints and existing greedy/beam public planners',
        'claim':'explicit simulated post-exposure S union T world; no anatomical or clinical validation',
        'cost_scope':'per-method observed inference/search costs plus separately reported upstream TRAIN cost; no equal-cost claim',
        'source_index':{'path':relative(HERE/'source-index.json'),'sha256':None}}
    encode=lambda value:(json.dumps(value,indent=2,sort_keys=True,allow_nan=False)+'\n').encode()
    index_raw=encode(index);release['source_index']['sha256']=hashlib.sha256(index_raw).hexdigest()
    release_raw=encode(release)
    # Exclusive writes preserve any partial finalization as evidence; never
    # overwrite the pending candidate, a previous final freeze or an attempt.
    with (HERE/'source-index.json').open('xb') as stream:stream.write(index_raw)
    with (HERE/'release-template.json').open('xb') as stream:stream.write(release_raw)
    print(json.dumps({'status':'pending_root_release','head':head,'source_count':len(bindings),
        'metadata_count':len(metadata),'model_loads':0,'patient_array_reads':0,
        'source_index_sha256':hashlib.sha256(index_raw).hexdigest(),
        'release_template_sha256':hashlib.sha256(release_raw).hexdigest()},indent=2))

if __name__=='__main__':main()
